require'nvim-treesitter.configs'.setup {
  highlight = {
    enable = true,              -- false will disable the whole extension
  },
  indent = {
    enable = true,
  },
  ensure_installed = {
    "c",
    "cpp",
    "rust",
    "bash",
    "c_sharp",
    "cmake",
    "comment",
    "commonlisp",
    "css",
    "dockerfile",
    "fish",
    "html",
    "java",
    "javascript",
    "jsdoc",
    "json",
    "json5",
    "latex",
    "lua",
    "make",
    "markdown",
    "perl",
    "php",
    "python",
    "regex",
    "ruby",
    "scss",
    "sql",
    "toml",
    "typescript",
    "vim",
    "vue",
    "yaml",
  },
  sync_install = true,
  auto_install = true,
}
